
trigger:
  branches:
    include:
      - main

variables:
  - group: github_Credi

stages:
- stage: SyncToGitHub
  displayName: 'Sync Azure DevOps Repo to GitHub'
  jobs:
  - job: MirrorJob
    displayName: 'Mirror to GitHub'
    pool:
      name: Default
    steps:
    - checkout: self
    - script: |        
        git remote add github https://$(GITHUB_PAT)@github.com/smaliaquib/$(Build.Repository.Name).git

        git push github HEAD:main --force
      displayName: 'Push to GitHub'




# git remote add devops https://aquibalicool4@dev.azure.com/aquibalicool4/Perceptr/_git/Perceptr
# git branch -vv                                                                                                                         
#  git push --set-upstream devops main  




# git remote add devops https://aquibalicool4@dev.azure.com/aquibalicool4/Perceptr/_git/Perceptr
# git branch -vv                                                                                                                         
# git push --set-upstream devops main  
