trigger:
  branches:
    include:
    - develop-01

variables:
- group: github_Credi

stages:
- stage: SyncToGitHub
  displayName: 'Sync Azure DevOps Repo to GitHub'
  jobs:
  - job: MirrorJob
    displayName: 'Mirror to GitHub'
    pool:
      name: Default
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      persistCredentials: true
    
    - bash: |
        git config --global user.email "aquibalicool3@gmail.com"
        git config --global user.name "smaliaquib"
        
        # Verify we're on the right branch
        git branch -a
        git status
        
        # Remove github remote if it exists
        git remote remove github 2>/dev/null || echo "Remote not found"
        
        # Add github remote with PAT
        git remote add github https://$(GITHUB_PAT)@github.com/smaliaquib/Perceptra.git
        
        # Create a clean temporary directory for clone
        cd ..
        git clone --bare $(Build.Repository.Uri) temp-repo
        cd temp-repo
        
        # Push mirror to GitHub
        git push --mirror https://$(GITHUB_PAT)@github.com/smaliaquib/Perceptra.git --force
      displayName: 'Push to GitHub'
      
# trigger:
#   branches:
#     include:
#       - main

# variables:
#   - group: github_Credi

# stages:
# - stage: SyncToGitHub
#   displayName: 'Sync Azure DevOps Repo to GitHub'
#   jobs:
#   - job: MirrorJob
#     displayName: 'Mirror to GitHub'
#     pool:
#       name: Default
#     steps:
#     - checkout: self
#     - script: |        
#         git remote add github https://$(GITHUB_PAT)@github.com/smaliaquib/$(Build.Repository.Name).git

#         git push github HEAD:main --force
#       displayName: 'Push to GitHub'




# git remote add devops https://aquibalicool4@dev.azure.com/aquibalicool4/Perceptr/_git/Perceptr
# git branch -vv                                                                                                                         
#  git push --set-upstream devops main  




# git remote add devops https://aquibalicool4@dev.azure.com/aquibalicool4/Perceptr/_git/Perceptr
# git branch -vv                                                                                                                         
# git push --set-upstream devops main  
